// <auto-generated />
using System;
using Foundation.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundationAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220410151813_CorrectedColumnInPlanets")]
    partial class CorrectedColumnInPlanets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Foundation.Core.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CharacterId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc315eaa-bfa2-4c07-a7e6-b3685b50fb3d"),
                            Name = "Hari Seldon",
                            PlanetId = new Guid("88521e15-f778-4b17-b155-2386e30b1971")
                        },
                        new
                        {
                            Id = new Guid("4f0fc21b-b88b-4f7d-a49e-bf662ec99500"),
                            Name = "Gaal Dornick",
                            PlanetId = new Guid("9fea1bd8-f221-4856-8b0b-a8945afd352f")
                        },
                        new
                        {
                            Id = new Guid("62c94733-e9a6-4789-867f-1cb3f38ddeca"),
                            Name = "Anselm Haut Rodric",
                            PlanetId = new Guid("45f87d18-afb5-47c5-a2a3-166cdff67c5d")
                        });
                });

            modelBuilder.Entity("Foundation.Core.Entities.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanetId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fea1bd8-f221-4856-8b0b-a8945afd352f"),
                            Name = "Synnax"
                        },
                        new
                        {
                            Id = new Guid("88521e15-f778-4b17-b155-2386e30b1971"),
                            Name = "Trantor"
                        },
                        new
                        {
                            Id = new Guid("a8576e1b-d866-40a5-9820-45d31383748a"),
                            Name = "Terminus"
                        },
                        new
                        {
                            Id = new Guid("45f87d18-afb5-47c5-a2a3-166cdff67c5d"),
                            Name = "Anacreon"
                        },
                        new
                        {
                            Id = new Guid("9d56a7df-b544-4081-9139-94aa4816563b"),
                            Name = "Smyrno"
                        },
                        new
                        {
                            Id = new Guid("09ae2f6c-7c43-4a91-b6ab-75dfb68d7ab0"),
                            Name = "Konom"
                        },
                        new
                        {
                            Id = new Guid("2078939d-b339-482f-9b80-958466b4c94f"),
                            Name = "Daribow"
                        },
                        new
                        {
                            Id = new Guid("a62e90a9-f3a9-4e5a-aceb-fa342aa18a3c"),
                            Name = "Askone"
                        },
                        new
                        {
                            Id = new Guid("fbd5937c-8641-440c-a3d1-d85230a4f1c8"),
                            Name = "Korell"
                        },
                        new
                        {
                            Id = new Guid("cd56c939-c820-4140-903c-2e3ec1025e8f"),
                            Name = "Siwenna"
                        });
                });

            modelBuilder.Entity("Foundation.Core.Entities.Character", b =>
                {
                    b.HasOne("Foundation.Core.Entities.Planet", "Planet")
                        .WithMany("Characters")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Foundation.Core.Entities.Planet", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
